# Generated by Django 2.2 on 2020-05-17 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postlike',
            old_name='post',
            new_name='posts',
        ),
    ]
